# Generated by Django 4.0 on 2024-02-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='post/thumbnail', verbose_name='Thumbnail')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
        ),
    ]
