# Generated by Django 4.0 on 2024-02-02 14:09

import ckeditor_uploader.fields
import tinymce
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='details',
        ),
        migrations.AddField(
            model_name='services',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
