# Generated by Django 4.2.9 on 2024-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_services_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
