# Generated by Django 4.2.9 on 2024-02-20 20:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_department_portfoliocategory_services_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
