# Generated by Django 4.2.9 on 2024-03-03 21:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_services_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='carousel/thumbnail', verbose_name='Thumbnail')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='department/thumbnail', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='department',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
