# Generated by Django 4.2.9 on 2024-03-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_carousel_department_content_department_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='department',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Name of the flaticon', max_length=200, null=True),
        ),
    ]
