# Generated by Django 4.2.9 on 2024-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_services_options_alter_department_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='headline',
            field=models.BooleanField(default=False),
        ),
    ]
