# Generated by Django 4.2.9 on 2024-03-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_department_headline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='draft', max_length=10),
        ),
    ]
