# Generated by Django 4.2.9 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_delete_portfoliocategory_department_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenmarkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('services', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
